### ISSUE TITLE
Strange error with run_student

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#105]
I have this error with run_student. Could it be a version mismatch between the external docker and the one assumed by the run_student script ?

Why is run_student provided by the container and not mounted (read-only) from the current version of inginious ?

```
Traceback (most recent call last):
File "/usr/bin/run_student", line 96, in 
  <module> args.share_network)
File "/usr/lib/python2.7/site-packages/rpyc/core/netref.py", line 196, in __call__
  return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
File "/usr/lib/python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
  return conn.sync_request(handler, oid, *args)
File "/usr/lib/python2.7/site-packages/rpyc/core/protocol.py", line 441, in sync_request
  raise obj
IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/memory/docker/3c26b4572db0be7341d8d4b34da6826d6935aba97606f232845225a638bc1f32/memory.oom_control' 

========= Remote Traceback (1) ========= 
Traceback (most recent call last):
File "/nix/store/a2v1c2gf7mpl1nki5ag69f618hrx6svd-python2.7-rpyc-3.3.0/lib/python2.7/site-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
  res = self._HANDLERS[handler](self, *args)
File "/nix/store/a2v1c2gf7mpl1nki5ag69f618hrx6svd-python2.7-rpyc-3.3.0/lib/python2.7/site-packages/rpyc/core/protocol.py", line 535, in _handle_call
  return self._local_objects[oid](*args, **dict(kwargs))
File "/nix/store/l3m5wrzg971pqi9p3rykbcpkcr0rq22g-python2.7-inginious-0.3a2.dev0/lib/python2.7/site-packages/inginious/backend/agent/simple_agent.py", line 607, in exposed_run
  int(hard_time_limit), bool(share_network), parent_container_id, container_set, student_path)
File "/nix/store/l3m5wrzg971pqi9p3rykbcpkcr0rq22g-python2.7-inginious-0.3a2.dev0/lib/python2.7/site-packages/inginious/backend/agent/simple_agent.py", line 534, in _create_new_student_container
  self._memory_watcher.add_container_memory_limit(container_id, mem_limit)
File "/nix/store/l3m5wrzg971pqi9p3rykbcpkcr0rq22g-python2.7-inginious-0.3a2.dev0/lib/python2.7/site-packages/inginious/backend/agent/_cgroup_helper.py", line 69, in add_container_memory_limit
  self._containers_running[container_id] = {"eventlistener": cgroup.EventListener(cg, 'memory.oom_control'),
File "/nix/store/0md1hf4ksk0w29gs9a9w8g8afiji4iz4-python2.7-cgroup-utils-0.6/lib/python2.7/site-packages/cgutils/cgroup.py", line 767, in __init__
  self.target_file = open(target_path)
IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/memory/docker/3c26b4572db0be7341d8d4b34da6826d6935aba97606f232845225a638bc1f32/memory.oom_control' 

```

**Comment by layus** [comment]
This seems to be a transient timing problem. When the system is under heavy load, the error does not occur.
It looks like a race condition somewhere around run_student.

**Comment by GuillaumeDerval** [comment]
That's a race condition with cgroup :O

**Comment by GuillaumeDerval** [comment]
It would seem that we don't wait (enough) for the container creation, or the container creation fails somewhere. As such, the cgroup is not yet created.

**Comment by layus** [comment]
There is nothing indicating a container creation failed, and I actually see the second container spawning (`watch ls /sys/fs/cgroup...`). Sadly I have no idea on how to solve this.

**Comment by layus** [comment]
My observations show that `/sys/fs/cgroup/memory/docker/3c26b4572db0be7341d8d4b34da6826d6935aba97606f232845225a638bc1f32` exists, but does not contain `memory.oom_control`. Only `tasks` and one other (pseudo-)file.
Does it help ?

**Comment by layus** [comment]
This makes sense, because if `/sys/fs/cgroup/memory/docker/3c26b4572db0be7341d8d4b34da6826d6935aba97606f232845225a638bc1f32` did not exist, then [get_container_cgroup("memory", container_id)](https://github.com/UCL-INGI/INGInious/blob/master/inginious/backend/agent/_cgroup_helper.py#L67) would return None, and the code would fail for a well-known reason :-).

**Comment by layus** [comment]
running `while :; do tree /sys/fs/cgroup/memory/docker/*/; done` shows that the cgroup exists and contains the right files.
Strange thing is, get_container_cgroup returned the right cgroup (so it must exist, right ?), but it does not exist anymore when `cgroup.EventListener(cg, 'memory.oom_control')` is called.
The only thing that occur in between is tacking a lock. Could the container finish its job in the meantime?

I got only two correct runs out of 300 attempts (it is the first "hello world!" demo task).

**Comment by GuillaumeDerval** [comment]
Can you try with a "sleep" in the hello world? I think you are right, the container may have finished before INGInious opens the file.

**Comment by layus** [comment]
Indeed, the following code works all the time (that is, 5 out of 5 attemps, which is about the same considering the previous results of 2 out of 300 :-)).
```python
import time
time.sleep(1)
print 'Hello World!'
```

**Comment by GuillaumeDerval** [comment]
Ok, nice troubleshooting :-)

That's somewhat scary to see such a bug exists... that's what happens when you develop on OS X with Docker in a VM and have as only production instance a linux VM with devicemapper as FS.

I don't really see an easy way to solve the bug (we should have a way to indicate that INGInious has successfully bound the container before the internal script really starts), and neither @anthonygego nor me have time to invest on that now... Will be the first thing I do after June 24th ;-)

PRs are welcome in the meantime :D

**Comment by layus** [comment]
Now that I have a work-around, I can wait one or two months :-D

**Comment by GuillaumeDerval** [comment]
@layus Does it completely fix your problem?

**Comment by layus** [comment]
This really helps in the case of this issue, but is not enough. I was able to get errors like this one about once every 10 tries.
Looks like a race condition in cgroup-utils itself. Neat :-).
```
Traceback (most recent call last):
  File "/usr/bin/run_student", line 96, in &lt;module&gt;
    args.share_network)
  File "/usr/lib/python2.7/site-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/site-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/memory/docker/79813d056c3b8d71aadbf63f52840b59e2f87a3a6ea4aa74e648766d6e3cb91a/cgroup.procs'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/nix/store/ayi3q4nn0vgdd9mpvhfd7iv4gjpjjcvh-python2.7-rpyc-3.3.0/lib/python2.7/site-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/nix/store/ayi3q4nn0vgdd9mpvhfd7iv4gjpjjcvh-python2.7-rpyc-3.3.0/lib/python2.7/site-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/nix/store/rawpr8v1f05cab4nfhz0n6yyqb7z50ap-inginious-0.3a2.dev0/lib/python2.7/site-packages/inginious/backend/agent/simple_agent.py", line 607, in exposed_run
    int(hard_time_limit), bool(share_network), parent_container_id, container_set, student_path)
  File "/nix/store/rawpr8v1f05cab4nfhz0n6yyqb7z50ap-inginious-0.3a2.dev0/lib/python2.7/site-packages/inginious/backend/agent/simple_agent.py", line 534, in _create_new_student_container
    self._memory_watcher.add_container_memory_limit(container_id, mem_limit)
  File "/nix/store/rawpr8v1f05cab4nfhz0n6yyqb7z50ap-inginious-0.3a2.dev0/lib/python2.7/site-packages/inginious/backend/agent/_cgroup_helper.py", line 67, in add_container_memory_limit
    cg = get_container_cgroup("memory", container_id)
  File "/nix/store/rawpr8v1f05cab4nfhz0n6yyqb7z50ap-inginious-0.3a2.dev0/lib/python2.7/site-packages/inginious/backend/agent/_cgroup_helper.py", line 46, in get_container_cgroup
    cgroup_obj = cgroup.scan_cgroups(cgroupname)
  File "/nix/store/cc3jarv56ifk2fszihdw5kw4lb5f4s6x-python2.7-cgroup-utils-0.6/lib/python2.7/site-packages/cgutils/cgroup.py", line 840, in scan_cgroups
    return _scan_cgroups_recursive(subsystem, mount_point, mount_point, filters)
  File "/nix/store/cc3jarv56ifk2fszihdw5kw4lb5f4s6x-python2.7-cgroup-utils-0.6/lib/python2.7/site-packages/cgutils/cgroup.py", line 809, in _scan_cgroups_recursive
    mount_point, filters)
  File "/nix/store/cc3jarv56ifk2fszihdw5kw4lb5f4s6x-python2.7-cgroup-utils-0.6/lib/python2.7/site-packages/cgutils/cgroup.py", line 809, in _scan_cgroups_recursive
    mount_point, filters)
  File "/nix/store/cc3jarv56ifk2fszihdw5kw4lb5f4s6x-python2.7-cgroup-utils-0.6/lib/python2.7/site-packages/cgutils/cgroup.py", line 802, in _scan_cgroups_recursive
    cgroup = CGroup(subsystem, fullpath=fullpath, filters=filters)
  File "/nix/store/cc3jarv56ifk2fszihdw5kw4lb5f4s6x-python2.7-cgroup-utils-0.6/lib/python2.7/site-packages/cgutils/cgroup.py", line 616, in __init__
    self.update()
  File "/nix/store/cc3jarv56ifk2fszihdw5kw4lb5f4s6x-python2.7-cgroup-utils-0.6/lib/python2.7/site-packages/cgutils/cgroup.py", line 700, in update
    pids = fileops.readlines(self.paths['cgroup.procs'])
  File "/nix/store/cc3jarv56ifk2fszihdw5kw4lb5f4s6x-python2.7-cgroup-utils-0.6/lib/python2.7/site-packages/cgutils/fileops.py", line 29, in readlines
    with open(path) as f:
IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/memory/docker/79813d056c3b8d71aadbf63f52840b59e2f87a3a6ea4aa74e648766d6e3cb91a/cgroup.procs'
```

**Comment by GuillaumeDerval** [comment]
You're right, it's a race condition between Docker and cgroup-utils; but we can still safely ignore it :-)

**Comment by layus** [comment]
Seems to be ok: no failure in one hundred tests.
That's as much certainty as testing can give ;-).
