### ISSUE TITLE
Can't open socket in fastcgi mode

### ISSUE THREAD

**Issue by mcanini** [UCL-INGI/INGInious#297]
It's unclear why the documentation suggests to configure 0.0.0.0:80 as the endpoint for the application. A socket on port 80 is created by lighttpd and thus the webapp cannot open it.
The application is still working though, so the issue seems minor.

```
/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
2018-02-17 09:28:19,637 - inginious.webapp - INFO - http://0.0.0.0:80/
2018-02-17 09:28:19,641 - inginious.client - INFO - Connecting to backend
2018-02-17 09:28:19,642 - inginious.backend - INFO - Agent b'\x00\x19I\\\xff' (Docker - Local agent) said hello
2018-02-17 09:28:19,642 - inginious.backend - DEBUG - Registering container java8scala for agent b'\x00\x19I\\\xff'
2018-02-17 09:28:19,642 - inginious.backend - DEBUG - Registering container java7 for agent b'\x00\x19I\\\xff'
2018-02-17 09:28:19,642 - inginious.backend - DEBUG - Sending containers updates...
2018-02-17 09:28:19,643 - inginious.backend - INFO - Agent b'\x00\x19I]\x00' (MCQ - Local agent) said hello
2018-02-17 09:28:19,643 - inginious.backend - DEBUG - Registering container mcq for agent b'\x00\x19I]\x00'
2018-02-17 09:28:19,643 - inginious.backend - DEBUG - Sending containers updates...
2018-02-17 09:28:19,643 - inginious.backend - INFO - New client connected b'\x00\xe2UX\xec'
2018-02-17 09:28:19,643 - inginious.backend - DEBUG - Sending containers updates...
2018-02-17 09:28:19,644 - inginious.client - INFO - Updated containers and batch containers
2018-02-17 09:28:19,644 - inginious.client - DEBUG - Containers: ('java8scala', 'mcq', 'java7')
2018-02-17 09:28:19,644 - inginious.client - DEBUG - Batch containers: {}
2018-02-17 09:28:29,643 - inginious.client - DEBUG - Asking for a job queue update
2018-02-17 09:28:29,644 - inginious.client - DEBUG - Received job queue update
2018-02-17 09:28:39,645 - inginious.client - DEBUG - Asking for a job queue update
2018-02-17 09:28:39,646 - inginious.client - DEBUG - Received job queue update
^CTraceback (most recent call last):
  File "/usr/local/bin/inginious-webapp", line 93, in <module>
    server.start()
  File "/usr/local/lib/python3.5/dist-packages/web/wsgiserver/wsgiserver3.py", line 1669, in start
    raise socket.error(msg)
OSError: No socket could be created -- (('0.0.0.0', 80): [Errno 13] Permission denied)
```

**Comment by anthonygego** [comment]
What version of ``flup`` and ``lighttpd`` package do you use ? 

It seems like the integrated webserver try to start after the flup server has been launched. This should not happen as ``flups.WSGIServer`` call has been blocking for a while.

**Comment by anthonygego** [comment]
I'll close this as there is no reply.
