### ISSUE TITLE
lti frontend failures should provide more information

### ISSUE THREAD

**Issue by donnm** [UCL-INGI/INGInious#301]
Following a stale link from the tool consumer leads to the following authentication failure:

```
(mod_fastcgi.c.2543) FastCGI-stderr: oauth2.Error: Expired timestamp: given 1520092182 and now 1520092941 has a greater difference than threshold 300
(mod_fastcgi.c.2543) FastCGI-stderr: During handling of the above exception, another exception occurred:
(mod_fastcgi.c.2543) FastCGI-stderr: Traceback (most recent call last):
(mod_fastcgi.c.2543) FastCGI-stderr:   File "/usr/local/lib/python3.5/dist-packages/inginious/frontend/lti/pages/utils.py", line 234, in _parse_lti_data
(mod_fastcgi.c.2543) FastCGI-stderr:     verified = verify_request_common(authorized_consumers, web.ctx.home + web.ctx.fullpath, "POST", {}, post_input)
(mod_fastcgi.c.2543) FastCGI-stderr:   File "/usr/local/lib/python3.5/dist-packages/inginious/common/customlibs/pylti.py", line 315, in verify_request_common
(mod_fastcgi.c.2543) FastCGI-stderr:     raise LTIException("OAuth error: Please check your key and secret")
(mod_fastcgi.c.2543) FastCGI-stderr: inginious.common.customlibs.pylti.LTIException: OAuth error: Please check your key and secret
(mod_fastcgi.c.2543) FastCGI-stderr: During handling of the above exception, another exception occurred:
(mod_fastcgi.c.2543) FastCGI-stderr: Traceback (most recent call last):
(mod_fastcgi.c.2543) FastCGI-stderr:   File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 257, in process
(mod_fastcgi.c.2543) FastCGI-stderr:     return self.handle()
(mod_fastcgi.c.2543) FastCGI-stderr:   File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 248, in handle
(mod_fastcgi.c.2543) FastCGI-stderr:     return self._delegate(fn, self.fvars, args)
(mod_fastcgi.c.2543) FastCGI-stderr:   File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 488, in _delegate
(mod_fastcgi.c.2543) FastCGI-stderr:     return handle_class(cls)
(mod_fastcgi.c.2543) FastCGI-stderr:   File "/usr/local/lib/python3.5/dist-packages/web/application.py", line 466, in handle_class
(mod_fastcgi.c.2543) FastCGI-stderr:     return tocall(*args)
(mod_fastcgi.c.2543) FastCGI-stderr:   File "/usr/local/lib/python3.5/dist-packages/inginious/frontend/lti/pages/utils.py", line 218, in POST
(mod_fastcgi.c.2543) FastCGI-stderr:     raise e
(mod_fastcgi.c.2543) FastCGI-stderr:   File "/usr/local/lib/python3.5/dist-packages/inginious/frontend/lti/pages/utils.py", line 214, in POST
(mod_fastcgi.c.2543) FastCGI-stderr:     self._parse_lti_data(courseid, taskid)
(mod_fastcgi.c.2543) FastCGI-stderr:   File "/usr/local/lib/python3.5/dist-packages/inginious/frontend/lti/pages/utils.py", line 237, in _parse_lti_data
(mod_fastcgi.c.2543) FastCGI-stderr:     raise Exception("Cannot authentify request (1)")
(mod_fastcgi.c.2543) FastCGI-stderr: Exception: Cannot authentify request (1)

```

The only thing returned to the browser is `internal server error` which is rather unhelpful for users who may have initiated the external tool link in the tool consumer and then actually clicked through some minutes later, causing the oauth token to expire.

**Comment by anthonygego** [comment]
Should be fixed. Additional docs were also written.
