### ISSUE TITLE
Unicode decode error in 'View submissions' view

### ISSUE THREAD

**Issue by bartwojcik** [UCL-INGI/INGInious#359]
I get an internal server error (apache) when trying to view submissions from course settings. Logs:
```
[Sun Sep 30 20:27:39.638237 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY] Traceback (most recent call last):
[Sun Sep 30 20:27:39.638283 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/web/application.py", line 257, in process
[Sun Sep 30 20:27:39.638291 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     return self.handle()
[Sun Sep 30 20:27:39.638296 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/web/application.py", line 248, in handle
[Sun Sep 30 20:27:39.638303 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     return self._delegate(fn, self.fvars, args)
[Sun Sep 30 20:27:39.638309 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/inginious/frontend/cookieless_app.py", line 92, in _delegate
[Sun Sep 30 20:27:39.638315 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     return super(CookieLessCompatibleApplication, self)._delegate(f, fvars, args[1:])
[Sun Sep 30 20:27:39.638321 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/web/application.py", line 488, in _delegate
[Sun Sep 30 20:27:39.638327 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     return handle_class(cls)
[Sun Sep 30 20:27:39.638332 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/web/application.py", line 466, in handle_class
[Sun Sep 30 20:27:39.638338 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     return tocall(*args)
[Sun Sep 30 20:27:39.638344 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/inginious/frontend/pages/utils.py", line 143, in GET
[Sun Sep 30 20:27:39.638350 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     return self.GET_AUTH(*args, **kwargs)
[Sun Sep 30 20:27:39.638355 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/inginious/frontend/pages/course_admin/submissions.py", line 50, in GET_AUTH
[Sun Sep 30 20:27:39.638362 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     return self.page(course)
[Sun Sep 30 20:27:39.638367 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/inginious/frontend/pages/course_admin/submissions.py", line 98, in page
[Sun Sep 30 20:27:39.638374 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     return self.template_helper.get_renderer().course_admin.submissions(course, tasks, users, classrooms, data, statistics, user_input, self._allowed_sort, self._allowed_sort_name, self._valid_formats, msgs, self.show_collapse(user_input))
[Sun Sep 30 20:27:39.638380 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/web/template.py", line 1034, in __getattr__
[Sun Sep 30 20:27:39.638385 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     t = self._template(name)
[Sun Sep 30 20:27:39.638391 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/web/template.py", line 1028, in _template
[Sun Sep 30 20:27:39.638413 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     self._cache[name] = self._load_template(name)
[Sun Sep 30 20:27:39.638419 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/home/inginious/.local/lib/python3.5/site-packages/web/template.py", line 1016, in _load_template
[Sun Sep 30 20:27:39.638425 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     return Template(open(path).read(), filename=path, **self._keywords)
[Sun Sep 30 20:27:39.638430 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
[Sun Sep 30 20:27:39.638435 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY]     return codecs.ascii_decode(input, self.errors)[0]
[Sun Sep 30 20:27:39.638440 2018] [wsgi:error] [pid 1145:tid 139877359372032] [remote XX.XXX.XXX.XXX:YYYYY] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 22233: ordinal not in range(128)
```
What may be the cause of it?

**Comment by GuillaumeDerval** [comment]
I cannot reproduce. Have you modified the template?

**Comment by GuillaumeDerval** [comment]
What is the value of your LOCALE env variable?

**Comment by anthonygego** [comment]
Indeed, if you are running under wgsi, you should check if the locale variables are set to UTF-8. Often Apache has its locale variables set to C by default.

**Comment by bartwojcik** [comment]
That did it, thanks guys.

I am a little surprised that by default (on debian?) apache uses non-system locale. Perhaps it is worth mentioning about in 'Webserver configuration' documentation section, so other users don't get hit by this as well?
