### ISSUE TITLE
inginious-install not found after pip3 install git+https://github.com/UCL-INGI/INGInious.git@v0.5

### ISSUE THREAD

**Issue by miun173** [UCL-INGI/INGInious#384]
I'm trying to install in my Ubuntu 18.04 using this commnad 
```
pip3 install git+https://github.com/UCL-INGI/INGInious.git@v0.5
```

The installation is successfull indicate by this message:
```
Successfully installed INGInious-0.5.dev0 Jinja2-2.10 ...
```

But, when i try to call `inginious-install` it's not found. Am I missing some steps?
Thanks

**Comment by anthonygego** [comment]
Are you running the pip command as root or local user ? With a virtualenv or not ? In some cases the pip path is not added in the system path. Check where pip copied the files.

**Comment by miun173** [comment]
> Are you running the pip command as root or local user ? With a virtualenv or not ? In some cases the pip path is not added in the system path. Check where pip copied the files.

I'm not using root when using pip3 and not using virtualenv. 
I've try to clone the repo and can install inginious. But, when i restart my pc and type `inginious-install` it return another error:
```
Traceback (most recent call last):
  File "/usr/local/bin/inginious-install", line 4, in <module>
    __import__('pkg_resources').run_script('INGInious==0.5.dev0', 'inginious-install')
  File "/home/miun/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/miun/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1435, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/inginious-install' not found in metadata at '/home/miun/.local/lib/python3.6/site-packages/INGInious-0.5.dev0-py3.6.egg-info'
```
