### ISSUE TITLE
Did non binary grades break something ? :-)

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#41]
With the most recent version of INGInious, I observe the following error when accessing the main page after having submitted some answers to the `[LTEST0000] Test tasks : H2G2 > Hello World!` task.

Also, the following screenshot shows that the display of the task is not correct. My grade is 0% despite the perfect second submission.

```
Traceback (most recent call last):
  File "/home/gmaudoux/.virtualenvs/inginious/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/home/gmaudoux/.virtualenvs/inginious/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/gmaudoux/.virtualenvs/inginious/lib/python2.7/site-packages/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/home/gmaudoux/.virtualenvs/inginious/lib/python2.7/site-packages/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "/home/gmaudoux/projets/INGInious/frontend/pages/index.py", line 42, in GET
    return self.call_main()
  File "/home/gmaudoux/projets/INGInious/frontend/pages/index.py", line 99, in call_main
    return renderer.main(open_courses, registerable_courses, except_free_last_submissions, registration_status)
  File "/home/gmaudoux/.virtualenvs/inginious/lib/python2.7/site-packages/web/template.py", line 1020, in template
    return self._base(t(*a, **kw))
  File "/home/gmaudoux/.virtualenvs/inginious/lib/python2.7/site-packages/web/template.py", line 881, in __call__
    return BaseTemplate.__call__(self, *a, **kw)
  File "/home/gmaudoux/.virtualenvs/inginious/lib/python2.7/site-packages/web/template.py", line 808, in __call__
    return self.t(*a, **kw)
  File "templates/main.html", line 67, in __template__
    $else:
  File "/home/gmaudoux/projets/INGInious/frontend/custom/courses.py", line 133, in get_user_grade
    cache = UserData(username).get_course_data(self.get_id())
  File "/home/gmaudoux/projets/INGInious/frontend/user_data.py", line 69, in get_course_data
    self.username]).get(
  File "/home/gmaudoux/projets/INGInious/frontend/user_data.py", line 111, in get_course_data_for_users
    result["task_grades"] = {dg["taskid"]: dg["grade"] for dg in result["task_grades"] if dg["taskid"] in user_tasks}
  File "/home/gmaudoux/projets/INGInious/frontend/user_data.py", line 111, in <dictcomp>
    result["task_grades"] = {dg["taskid"]: dg["grade"] for dg in result["task_grades"] if dg["taskid"] in user_tasks}
KeyError: 'grade'

127.0.0.1:51774 - - [12/Mar/2015 10:50:45] "HTTP/1.1 GET /" - 500 Internal Server Error
```

![inginious_bug](https://cloud.githubusercontent.com/assets/632767/6615727/c112417c-c8a6-11e4-9bce-bd43e2ac966a.png)

**Comment by GuillaumeDerval** [comment]
Did you try the new backend on the same DB? The "new backend" branch and "master" shares the same "db_version", leading the database to not being updated automatically.

**Comment by layus** [comment]
I dropped the db... That should be enough right ?

In fact you just need to enroll on a course then go back to the index.

**Comment by GuillaumeDerval** [comment]
```python
get_database().user_tasks.update({"succeeded": False, "grade": {"$exists": False}}, {"$set": {"grade": 0.0}}, multi=True)
get_database().user_tasks.update({"succeeded": True, "grade": {"$exists": False}}, {"$set": {"grade": 100.0}}, multi=True)
```
