### ISSUE TITLE
Web frontend fails when saving a task with a long description

### ISSUE THREAD

**Issue by lsignac** [UCL-INGI/INGInious#546]
The web frontend fails when clicking the save button on a task with a long description (>1000 chars) : 

>  Some error(s) occurred when saving the task:
>  * An internal error occurred

Server logs : 

~~~
Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/web.py-0.51>
    return self.handle()
  File "venv/lib/python3.8/site-packages/web.py-0.51>
    return self._delegate(fn, self.fvars, args)
  File "venv/lib/python3.8/site-packages/INGInious-0>
    input_data = web.input()
  File "venv/lib/python3.8/site-packages/web.py-0.51>
    out = rawinput(_method)
  File "venv/lib/python3.8/site-packages/web.py-0.51>
    a = cgiFieldStorage(fp=fp, environ=e, keep_blank_values=1)
  File "/usr/lib/python3.8/cgi.py", line 472, in __init__
    self.read_multi(environ, keep_blank_values, strict_parsing)
  File "/usr/lib/python3.8/cgi.py", line 647, in read_multi
    part = klass(self.fp, headers, ib, environ, keep_blank_values,
  File "/usr/lib/python3.8/cgi.py", line 474, in __init__
    self.read_single()
  File "/usr/lib/python3.8/cgi.py", line 670, in read_single
    self.read_lines()
  File "/usr/lib/python3.8/cgi.py", line 699, in read_lines
    self.read_lines_to_outerboundary()
  File "/usr/lib/python3.8/cgi.py", line 775, in read_lines_to_outerboundary
    self.__write(odelim + line)
  File "/usr/lib/python3.8/cgi.py", line 709, in __write
    self.file.write(data)
TypeError: a bytes-like object is required, not 'str'
~~~

The problem is related to web.py and cgi.py and has been discussed :

- <https://github.com/webpy/webpy/pull/575/>
- <https://github.com/webpy/webpy/issues/635> <= My version of web.py includes this buggy workaround

Note related to inginious but may be you can find a workaround ?

**Comment by GuillaumeDerval** [comment]
The actual issue is actually upstream in CPython (https://bugs.python.org/issue27777) ...

What you can do in the meantime is: reverting #575 in webpy and applying the patch https://github.com/python/cpython/pull/11764 to your Python install or monkeypatching it directly when INGInious starts.

I don't know how we handle it locally right now (@anthonygego can probably answer to that)

**Comment by lsignac** [comment]
Thank you for your answer.
Currently, I edit yaml files by hand (faster). So... I will wait for a fix in CPython.

**Comment by GuillaumeDerval** [comment]
Note that it also create problems when student submit big text answers in exercises.

**Comment by lsignac** [comment]
I did what you suggested and it worked. I hope this will be fixed soon in CPython. It's not a comfortable situation.
