### ISSUE TITLE
macOS: execution of 'Constant' statements is denied

### ISSUE THREAD

**Issue by vibhoothiiaanand** [UCL-INGI/INGInious#548]
Hi Team, 

Thanks for the tool, it looks promising, I have then set up the tool locally

- [x] Docker Installed and running? Yes working fine
- [x] inginious-install working? ?? Yes, working fine config file generated also, 

The problem arises when I try to deploy locally, gives us the following error with denied as logs when trying to run `inginious-webapp` and gives us 401 Unauthorized when running WebDAV with the config file(`inginious-webdav --config  configuration.yaml`) tried to make the different user/multiple combos, still not getting logged-in.

In short, gives error from
`/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/inginious/frontend/templates/internalerror.html:39 - execution of 'Constant' statements is denied` For almost all lines of the file `internalerror.html `

Traceback:

<Details>

```python
Rraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/web/application.py", line 289, in process
    return self.handle()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/web/application.py", line 280, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/inginious/frontend/cookieless_app.py", line 143, in _delegate
    return super(CookieLessCompatibleApplication, self)._delegate(f, fvars, args[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/web/application.py", line 530, in _delegate
    return handle_class(cls)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/web/application.py", line 508, in handle_class
    return tocall(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/inginious/frontend/pages/courselist.py", line 16, in GET
    return self.show_page()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/inginious/frontend/pages/courselist.py", line 32, in show_page
    return self.template_helper.get_renderer().index(open_courses, user_info)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/web/template.py", line 1135, in __getattr__
    t = self._template(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/web/template.py", line 1129, in _template
    self._cache[name] = self._load_template(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/web/template.py", line 1107, in _load_template
    return Template(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/web/template.py", line 942, in __init__
    code = self.compile_template(text, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/web/template.py", line 1033, in compile_template
    SafeVisitor().walk(ast_node, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/web/template.py", line 1366, in walk
    raise SecurityError("\n".join([str(err) for err in self.errors]))
```
</Details>

Config.yaml

```yaml
backend: local
backup_directory: .
local-config: {}
mongo_opt:
    database: INGInious
    host: localhost
plugins: []
superadmins:
- admin
tasks_directory: .
use_minified_js: true
```

Also, I have explicitly ran the certificates from python folder: `'/Applications/Python 3.8/Install Certificates.command'` which was +1 with no errors.

I am not quite sure if it is my configuration issue or upstream issue.

Please do let me know if I require to provide more info.

Best,
Vibhoothi

Edit:
Adding missing link: https://paste.ubuntu.com/p/z67Jv8XMG8/

**Comment by anthonygego** [comment]
There are still several issues remaining with web.py and python 3.8. I strongly suggest you to set up a python3.7 environment with web.py 0.40 in the meantime.

**Comment by vibhoothiiaanand** [comment]
@anthonygego Thanks,
With 3.7 it works well,

But I am not able to execute any codes 

Logs:

<Details>

```python


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cheroot/server.py", line 1277, in communicate
    req.respond()
  File "/usr/local/lib/python3.7/site-packages/cheroot/server.py", line 1073, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.7/site-packages/cheroot/wsgi.py", line 145, in respond
    for chunk in filter(None, response):
RuntimeError: generator raised StopIteration
2020-08-03 23:22:22,058 - inginious.webapp.submissions - INFO - New submission from superadmin - superadmin@inginious.org - tutorial/01_getting_started - ::1
2020-08-03 23:22:22,061 - inginious.backend - INFO - Adding a new job b'\x001\x13\xc3\x98' 3c0b7901-69d1-4474-992f-fe6fa11b08ed to the queue
2020-08-03 23:22:22,061 - inginious.backend - INFO - Sending job b'\x001\x13\xc3\x98' 3c0b7901-69d1-4474-992f-fe6fa11b08ed to agent b'\x00\xd5\xe89\x18'
2020-08-03 23:22:22,061 - inginious.webapp.requests - INFO - ::1:50327 - "HTTP/1.1 POST /course/tutorial/01_getting_started" - 200 OK
2020-08-03 23:22:22,063 - inginious.agent.docker - INFO - Received request for jobid (b'\x001\x13\xc3\x98', '3c0b7901-69d1-4474-992f-fe6fa11b08ed')
2020-08-03 23:22:22,064 - inginious.agent.docker - INFO - Received request for jobid (b'\x001\x13\xc3\x98', '3c0b7901-69d1-4474-992f-fe6fa11b08ed')
2020-08-03 23:22:23,168 - inginious.webapp.requests - INFO - ::1:50327 - "HTTP/1.1 POST /course/tutorial/01_getting_started" - 200 OK
2020-08-03 23:22:23,889 - inginious.agent.docker - WARNING - Container 076b09a110c76b24d3b533a88de4ace00beb34a79c3844189e5d3d846b492b26 has not given any result
2020-08-03 23:22:23,890 - inginious.agent.docker - ERROR - Cannot get back output of container 076b09a110c76b24d3b533a88de4ace00beb34a79c3844189e5d3d846b492b26! ('NoneType' object has no attribute 'items')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/inginious/agent/docker_agent/__init__.py", line 574, in handle_job_closing
    for key, item in return_value.items():
AttributeError: 'NoneType' object has no attribute 'items'
2020-08-03 23:22:23,939 - inginious.backend - INFO - Job b'\x001\x13\xc3\x98' 3c0b7901-69d1-4474-992f-fe6fa11b08ed finished on agent b'\x00\xd5\xe89\x18'
2020-08-03 23:22:24,221 - inginious.webapp.requests - INFO - ::1:50327 - "HTTP/1.1 POST /course/tutorial/01_getting_started" - 200 OK

```
</Details>

Log2: 
```
An internal error occurred. Please retry later. If the error persists, send an email to the course administrator. [Submission #5f284ed66cd45d7687cb6e27]
The grader did not return a readable output : 'NoneType' object has no attribute 'items'
```

Screenshot: ![Screenshot 2020-08-03 at 11 23 57 PM](https://user-images.githubusercontent.com/10833993/89212045-6ad5ab80-d5e0-11ea-8a95-2d610f68ae6e.png)
Same error happens when I try to do Start Remote SSH Console with this input
Logs for the same:

<Details>

```python
726827 to the queue
2020-08-03 23:24:19,707 - inginious.webapp.submissions - INFO - New submission from superadmin - superadmin@inginious.org - tutorial/01_getting_started - ::1
2020-08-03 23:24:19,707 - inginious.backend - INFO - Sending job b'\x001\x13\xc3\x98' 6c5d51b7-4b62-4f44-bcda-664717726827 to agent b'\x00\xd5\xe89\x18'
2020-08-03 23:24:19,709 - inginious.webapp.requests - INFO - ::1:50349 - "HTTP/1.1 POST /course/tutorial/01_getting_started" - 200 OK
2020-08-03 23:24:19,711 - inginious.agent.docker - INFO - Received request for jobid (b'\x001\x13\xc3\x98', '6c5d51b7-4b62-4f44-bcda-664717726827')
2020-08-03 23:24:19,712 - inginious.agent.docker - INFO - Received request for jobid (b'\x001\x13\xc3\x98', '6c5d51b7-4b62-4f44-bcda-664717726827')
2020-08-03 23:24:20,735 - inginious.webapp.requests - INFO - ::1:50349 - "HTTP/1.1 POST /course/tutorial/01_getting_started" - 200 OK
2020-08-03 23:24:21,160 - inginious.agent.docker - WARNING - Container f0c4c5453f2792cd09cfb3dbb8b22f4215bc581464e4fc33c6375fe877fe7fd4 has not given any result
2020-08-03 23:24:21,161 - inginious.agent.docker - ERROR - Cannot get back output of container f0c4c5453f2792cd09cfb3dbb8b22f4215bc581464e4fc33c6375fe877fe7fd4! ('NoneType' object has no attribute 'items')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/inginious/agent/docker_agent/__init__.py", line 574, in handle_job_closing
    for key, item in return_value.items():
AttributeError: 'NoneType' object has no attribute 'items'
2020-08-03 23:24:21,213 - inginious.backend - INFO - Job b'\x001\x13\xc3\x98' 6c5d51b7-4b62-4f44-bcda-664717726827 finished on agent b'\x00\xd5\xe89\x18'
2020-08-03 23:24:21,763 - inginious.webapp.requests - INFO - ::1:50349 - "HTTP/1.1 POST /course/tutorial/01_getting_started" - 200 OK
```
</Details>


PS: I have installed the containers when doing the install, also installed the extra C++ one too. It was successful in installing.

**Comment by anthonygego** [comment]
You may want to check that both the msgpack version in your frontend setup and in the container are the same by running ``pip show msgpack``. They should be. The v0.6 branch rely on msgpack < 1.0 while the master branch rely on msgpack 1.0 and I'm not sure both are uploaded on docker hub right now. @Drumor does the jenkins autobuild push both versions on docker hub ?

A quick fix is to build your container manually by running ``docker build -t ingi/inginious-c-<folder> <folder>``. The base containers are located in this repo under the ``base-containers`` folder while the other ones are located in the UCL-INGI/INGInious-containers repo.

**Comment by pchaow** [comment]
I update webpy to latest version (0.6.1) and this problem is solve. But I'm not sure that cause another error.
