### ISSUE TITLE
I do not see the 'tutorial' course

### ISSUE THREAD

**Issue by erelsgl** [UCL-INGI/INGInious#644]
When I installed inginious, I asked to download the tutorial course, and indeed I see its folder inside the inginious folder:

```
# ls -la /var/www/inginious
total 60
drwxr-xr-x  4 www-data www-data  4096 Feb 24 15:28 .
drwxr-xr-x  4 root     root      4096 Feb 24 15:05 ..
-rw-rw-r--  1 www-data www-data 34520 Feb 23 15:32 LICENSE
-rw-rw-r--  1 www-data www-data   131 Feb 23 15:32 README.rst
drwxr-xr-x  2 www-data www-data  4096 Feb 24 15:28 agent_tmp
-rw-r--r--  1 www-data www-data   187 Feb 24 15:18 configuration.yaml
drwxrwxr-x 15 www-data www-data  4096 Feb 24 15:13 tutorial
```

But, when I login as a superadmin, I do not see any course.

**Comment by erelsgl** [comment]
I found this error in the error.log:

```
[Sun Feb 28 08:04:01.584060 2021] [wsgi:error] [pid 23936:tid 140201397536512] [client 93.172.65.8:33104] Traceback (most recent call last):
[Sun Feb 28 08:04:01.584070 2021] [wsgi:error] [pid 23936:tid 140201397536512] [client 93.172.65.8:33104]   File "/usr/local/lib/python3.6/dist-packages/inginious/common/course_factory.py", line 92, in get_all_courses
[Sun Feb 28 08:04:01.584093 2021] [wsgi:error] [pid 23936:tid 140201397536512] [client 93.172.65.8:33104]     output[courseid] = self.get_course(courseid)
[Sun Feb 28 08:04:01.584113 2021] [wsgi:error] [pid 23936:tid 140201397536512] [client 93.172.65.8:33104]   File "/usr/local/lib/python3.6/dist-packages/inginious/common/course_factory.py", line 36, in get_course
[Sun Feb 28 08:04:01.584125 2021] [wsgi:error] [pid 23936:tid 140201397536512] [client 93.172.65.8:33104]     self._update_cache(courseid)
[Sun Feb 28 08:04:01.584134 2021] [wsgi:error] [pid 23936:tid 140201397536512] [client 93.172.65.8:33104]   File "/usr/local/lib/python3.6/dist-packages/inginious/common/course_factory.py", line 184, in _update_cache
[Sun Feb 28 08:04:01.584143 2021] [wsgi:error] [pid 23936:tid 140201397536512] [client 93.172.65.8:33104]     path_to_descriptor = self._get_course_descriptor_path(courseid)
[Sun Feb 28 08:04:01.584152 2021] [wsgi:error] [pid 23936:tid 140201397536512] [client 93.172.65.8:33104]   File "/usr/local/lib/python3.6/dist-packages/inginious/common/course_factory.py", line 110, in _get_course_descriptor_path
[Sun Feb 28 08:04:01.584161 2021] [wsgi:error] [pid 23936:tid 140201397536512] [client 93.172.65.8:33104]     raise CourseNotFoundException()
[Sun Feb 28 08:04:01.584256 2021] [wsgi:error] [pid 23936:tid 140201397536512] [client 93.172.65.8:33104] inginious.common.exceptions.CourseNotFoundException
```

**Comment by anthonygego** [comment]
Are there any files in the ``tutorial`` folder ?

**Comment by erelsgl** [comment]
Yes, here:

```
drwxrwxr-x  3 www-data www-data 4096 Feb 24 15:13 '$common'
drwxrwxr-x 15 www-data www-data 4096 Feb 24 15:13  .
drwxr-xr-x  4 www-data www-data 4096 Feb 24 15:28  ..
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  01_getting_started
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  02_courses
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  03_tasks
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  04_run_student
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  05_fetching_input
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  06_parsing_template
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  07_random_inputs
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  08_feedback
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  09_advance_feedback
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  10_archive
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  11_ssh_debug
drwxrwxr-x  2 www-data www-data 4096 Feb 24 15:13  12_environments
-rw-rw-r--  1 www-data www-data  967 Feb 23 15:32  course.yaml
```

(this is the default that was created during installation; I did not change it)

**Comment by anthonygego** [comment]
I realize we might have pushed breaking changes in the tutorial by updating it recently as the tagging mechanism architecture have changed since. This exception is also returned in case of bad parsing. Have a try with this version: https://github.com/UCL-INGI/INGInious-demo-tasks/tree/c9a74dfdc3b84ebd53a0456281c22c557ccdae6e

**Comment by erelsgl** [comment]
I checked out this commit. Now I do not see the $common folder:

```
drwxr-xr-x 12 www-data www-data 4096 Feb 28 10:59 .
drwxr-xr-x  4 www-data www-data 4096 Feb 28 10:59 ..
drwxr-xr-x  3 www-data www-data 4096 Feb 28 10:59 01_getting_started
drwxr-xr-x  2 www-data www-data 4096 Feb 28 10:59 02_courses
drwxr-xr-x  3 www-data www-data 4096 Feb 28 10:59 03_tasks
drwxr-xr-x  2 www-data www-data 4096 Feb 28 10:59 04_run_student
drwxr-xr-x  2 www-data www-data 4096 Feb 28 10:59 05_fetching_input
drwxr-xr-x  2 www-data www-data 4096 Feb 28 10:59 06_feedback
drwxr-xr-x  2 www-data www-data 4096 Feb 28 10:59 07_advance_feedback
drwxr-xr-x  2 www-data www-data 4096 Feb 28 10:59 08_archive
drwxr-xr-x  2 www-data www-data 4096 Feb 28 10:59 09_ssh_debug
drwxr-xr-x  2 www-data www-data 4096 Feb 28 10:59 10_environments
-rw-r--r--  1 www-data www-data   60 Feb 28 10:59 course.yaml
```

But I still have the same error.

**Comment by anthonygego** [comment]
Ensure that you specified an absolute path for the folders in the configuration file, otherwise the webserver will use its user homepath as the current working directory.

**Comment by anthonygego** [comment]
> I realize we might have pushed breaking changes in the tutorial by updating it recently as the tagging mechanism architecture have changed since. This exception is also returned in case of bad parsing.

Ensured by e576086523cbed1ea030e6cf720afc46b8e222e1
