### ISSUE TITLE
Can the agent be started reliably ? (or the random timeout)

### ISSUE THREAD

**Issue by layus** [UCL-INGI/INGInious#70]
I am a bit annoyed by the delay used in the tests to wait for the agent coming up.
On some build machine, the tests just stopped working and the build fails on the assert at https://github.com/UCL-INGI/INGInious/blob/master/inginious/backend/tests/TestJobManager.py#L120-L123

Apparently this already occurred on travis, as shown by https://github.com/UCL-INGI/INGInious/commit/58ac7c9680fe0aca0bdf04fec3716ff9db42b70f

Would it be possible not to rely on such an heuristic and start the agent reliably ? Or increase the wait time ?

**Comment by layus** [comment]
The full log can be accessed at http://hydra.nixos.org/build/25492707/nixlog/1/raw, and the issue is 

```
======================================================================
ERROR: inginious.backend.tests.TestRemoteAgentCrash.TestRemoteAgentAliasUpdateCrash.test_exception_alias
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/k50sy80yqz4baj0g9ga8h4xhm1509hp3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/nix/store/k50sy80yqz4baj0g9ga8h4xhm1509hp3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/util.py", line 470, in try_run
    return func()
  File "/tmp/nix-build-python2.7-inginious-0.3.dev1.drv-0/INGInious-0.3.dev1/inginious/backend/tests/TestJobManager.py", line 123, in setUp
    assert self.job_manager.number_agents_available() == 1
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Job Manager initialization done
Cannot connect to agent localhost-61008

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
AGENT/61008: INFO: server started on [0.0.0.0]:61008
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: inginious.backend.tests.TestRemoteAgentCrash.TestRemoteAgentJobCrash.test_exception_job
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/k50sy80yqz4baj0g9ga8h4xhm1509hp3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/nix/store/k50sy80yqz4baj0g9ga8h4xhm1509hp3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/util.py", line 470, in try_run
    return func()
  File "/tmp/nix-build-python2.7-inginious-0.3.dev1.drv-0/INGInious-0.3.dev1/inginious/backend/tests/TestJobManager.py", line 123, in setUp
    assert self.job_manager.number_agents_available() == 1
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Job Manager initialization done
Cannot connect to agent localhost-61009

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
AGENT/61009: INFO: server started on [0.0.0.0]:61009
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 106 tests in 200.431s

FAILED (errors=2, skipped=15)
building of ‘/nix/store/91sr72hcax6yff4276ji8bdr4mpjxhnl-python2.7-inginious-0.3.dev1’ timed out after 7200 seconds of silence
```

**Comment by GuillaumeDerval** [comment]
It seems it was a bug with the Job Manager, only attempting once to connect to the agent, after waiting 2 secs, which is probably too short for some machines. The long timeout in the test was completely unneeded...

**Comment by layus** [comment]
Ok, that makes sense :-). Not being able to connect within one minute and a half, even under heavy load, that was strange.

Thanks !
