### ISSUE TITLE
[agent_docker] Docker rlimits permission denied on macOS

### ISSUE THREAD

**Issue by anthonygego** [UCL-INGI/INGInious#898]
**Describe the bug**
A basic Docker install on macOS Ventura (M1) leads to the following error when running a submission : 

```
2022-11-29 14:19:10,432 - inginious.agent.docker - WARNING - Cannot start container! 500 Server Error for http+docker://localhost/v1.41/containers/c6925c36f1dd9a7b2c4f1ce091aef3507ac923154fdde9d84cdb4179a2205e63/start: Internal Server Error ("failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 7: operation not permitted: unknown")
Traceback (most recent call last):
  File "/Users/ogoletti/PycharmProjects/INGInious/venv/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/ogoletti/PycharmProjects/INGInious/venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/containers/c6925c36f1dd9a7b2c4f1ce091aef3507ac923154fdde9d84cdb4179a2205e63/start
```

**INGInious installation details**
- Version: 0.8.2+
- Containers version (if applicable): same

**To Reproduce**
1. Install and run Docker
2. Install and run INGInious with default options
3. Run the tutorial first task
4. Feedback "cannot create container"

**Expected behavior**
Expected feedback

**Comment by zvikfir** [comment]
I'm having the same issue. Is there a known fix to this?

**Comment by nrybowski** [comment]
For reference, the recommended solution for this issue is cleanly close the Docker Agent and logging an error.
See https://github.com/INGInious/INGInious/pull/1051#issuecomment-2980438214 for more details.
